---- MODULE NFQuorum_xstate ----
(*
 * .planning/formal/tla/NFQuorum_xstate.tla
 * GENERATED by bin/fsm-to-tla.cjs
 * Source: src/machines/nf-workflow.machine.ts
 * Regenerate: node bin/fsm-to-tla.cjs src/machines/nf-workflow.machine.ts --module=NFQuorum
 * Generated: 2026-03-17
 *
 * Machine id: nf-workflow
 * Framework:  xstate-v5
 * Initial state:     IDLE
 * States (4):          IDLE, COLLECTING_VOTES, DELIBERATING, DECIDED
 * Final states:      DECIDED
*)
EXTENDS Naturals, FiniteSets, TLC

\* ── Constants (model-checking bounds) ────────────────────────────────────────
CONSTANTS MaxBound  \* upper bound for event parameter quantifiers

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    slotsAvailable,  \* default: 0  annotation: event
    successCount,  \* default: 0  annotation: event
    deliberationRounds,  \* default: 0  annotation: deliberationRounds + 1
    maxDeliberation,  \* default: 9  annotation: const
    maxSize,  \* default: 3  annotation: (no annotation)
    polledCount  \* default: 0  annotation: (no annotation)

vars == <<state, slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Type invariant ────────────────────────────────────────────────────────────
\* @requirement QUORUM-01
TypeOK ==
    /\ state \in {"IDLE", "COLLECTING_VOTES", "DELIBERATING", "DECIDED"}
    /\ slotsAvailable \in Nat  \* FIXME: tighten bound if needed
    /\ successCount \in Nat  \* FIXME: tighten bound if needed
    /\ deliberationRounds \in Nat  \* FIXME: tighten bound if needed
    /\ maxDeliberation \in Nat  \* FIXME: tighten bound if needed
    /\ maxSize \in Nat  \* FIXME: tighten bound if needed
    /\ polledCount \in Nat  \* FIXME: tighten bound if needed

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "IDLE"
    /\ slotsAvailable = 0
    /\ successCount = 0
    /\ deliberationRounds = 0
    /\ maxDeliberation = 9
    /\ maxSize = 3
    /\ polledCount = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* IDLE -[QUORUM_START]-> COLLECTING_VOTES
IdleQuorumStart(a) ==
    /\ state = "IDLE"
    /\ state' = "COLLECTING_VOTES"
    /\ slotsAvailable' = a  \* param from event
    /\ polledCount' = polledCount  \* FIXME: XState assign for polledCount
    /\ UNCHANGED <<successCount, deliberationRounds, maxDeliberation, maxSize>>

\* IDLE -[CIRCUIT_BREAK]-> IDLE
IdleCircuitBreak ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[DECIDE]-> IDLE
IdleDecide ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* IDLE -[VOTES_COLLECTED]-> IDLE
IdleVotesCollected ==
    /\ state = "IDLE"
    /\ state' = "IDLE"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED / unanimityMet]-> DECIDED
CollectingVotesVotesCollectedToDECIDED(c) ==
    /\ state = "COLLECTING_VOTES"
    /\ c = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = c  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED]-> DELIBERATING
CollectingVotesVotesCollectedToDELIBERATING(c) ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "DELIBERATING"
    /\ successCount' = c  \* param from event
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[QUORUM_START]-> COLLECTING_VOTES
CollectingVotesQuorumStart ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[CIRCUIT_BREAK]-> COLLECTING_VOTES
CollectingVotesCircuitBreak ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[DECIDE]-> COLLECTING_VOTES
CollectingVotesDecide ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "COLLECTING_VOTES"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / unanimityMet]-> DECIDED
DeliberatingVotesCollectedToDECIDED(c) ==
    /\ state = "DELIBERATING"
    /\ c = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = c  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / noInfiniteDeliberation]-> DELIBERATING
DeliberatingVotesCollectedToDELIBERATING ==
    /\ state = "DELIBERATING"
    /\ deliberationRounds < maxDeliberation
    /\ state' = "DELIBERATING"
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, successCount, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED]-> DECIDED
DeliberatingVotesCollectedFallbackToDECIDED ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[DECIDE]-> DECIDED
DeliberatingDecide ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[QUORUM_START]-> DELIBERATING
DeliberatingQuorumStart ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[CIRCUIT_BREAK]-> DELIBERATING
DeliberatingCircuitBreak ==
    /\ state = "DELIBERATING"
    /\ state' = "DELIBERATING"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[DECIDE]-> DECIDED (self-loop in final state)
DecidedDecide ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[CIRCUIT_BREAK]-> DECIDED (self-loop in final state)
DecidedCircuitBreak ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[QUORUM_START]-> DECIDED (self-loop in final state)
DecidedQuorumStart ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED -[VOTES_COLLECTED]-> DECIDED (self-loop in final state)
DecidedVotesCollected ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED is a final (absorbing) state
StayDECIDED ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Next ──────────────────────────────────────────────────────────────────────
Next ==
    \/ \E a \in 0..MaxBound : IdleQuorumStart(a)
    \/ IdleCircuitBreak
    \/ IdleDecide
    \/ IdleVotesCollected
    \/ \E c \in 0..MaxBound : CollectingVotesVotesCollectedToDECIDED(c)
    \/ \E c \in 0..MaxBound : CollectingVotesVotesCollectedToDELIBERATING(c)
    \/ CollectingVotesQuorumStart
    \/ CollectingVotesCircuitBreak
    \/ CollectingVotesDecide
    \/ \E c \in 0..MaxBound : DeliberatingVotesCollectedToDECIDED(c)
    \/ DeliberatingVotesCollectedToDELIBERATING
    \/ DeliberatingVotesCollectedFallbackToDECIDED
    \/ DeliberatingDecide
    \/ DeliberatingQuorumStart
    \/ DeliberatingCircuitBreak
    \/ DecidedDecide
    \/ DecidedCircuitBreak
    \/ DecidedQuorumStart
    \/ DecidedVotesCollected
    \/ StayDECIDED

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
