---- MODULE QGSDQuorum_xstate ----
(*
 * .planning/formal/tla/QGSDQuorum_xstate.tla
 * GENERATED by bin/xstate-to-tla.cjs (hand-fixed for TLC compatibility)
 * Source: src/machines/qgsd-workflow.machine.ts
 * Regenerate: node bin/xstate-to-tla.cjs src/machines/qgsd-workflow.machine.ts --config=.planning/formal/tla/guards/qgsd-workflow.json --module=QGSDQuorum
 * Generated: 2026-03-05
 *
 * XState machine id: qgsd-workflow
 * Initial state:     IDLE
 * States (4):          IDLE, COLLECTING_VOTES, DELIBERATING, DECIDED
 * Final states:      DECIDED
*)
EXTENDS Naturals, FiniteSets, TLC

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    slotsAvailable,  \* default: 0  annotation: event
    successCount,  \* default: 0  annotation: event
    deliberationRounds,  \* default: 0  annotation: deliberationRounds + 1
    maxDeliberation,  \* default: 9  annotation: const
    maxSize,  \* default: 3  annotation: (no annotation)
    polledCount  \* default: 0  annotation: (no annotation)

vars == <<state, slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Type invariant ────────────────────────────────────────────────────────────
\* @requirement QUORUM-01
TypeOK ==
    /\ state \in {"IDLE", "COLLECTING_VOTES", "DELIBERATING", "DECIDED"}
    /\ slotsAvailable \in 0..4
    /\ successCount \in 0..4
    /\ deliberationRounds \in 0..10
    /\ maxDeliberation \in 0..10
    /\ maxSize \in 0..4
    /\ polledCount \in 0..4

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "IDLE"
    /\ slotsAvailable = 0
    /\ successCount = 0
    /\ deliberationRounds = 0
    /\ maxDeliberation = 9
    /\ maxSize = 3
    /\ polledCount = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* IDLE -[QUORUM_START]-> COLLECTING_VOTES
QuorumStart(sa_) ==
    /\ state = "IDLE"
    /\ state' = "COLLECTING_VOTES"
    /\ slotsAvailable' = sa_
    /\ polledCount' = polledCount
    /\ UNCHANGED <<successCount, deliberationRounds, maxDeliberation, maxSize>>

\* COLLECTING_VOTES -[VOTES_COLLECTED / unanimityMet]-> DECIDED
CollectingVotesToDecidedGuarded(sc_) ==
    /\ state = "COLLECTING_VOTES"
    /\ sc_ = polledCount  \* guard: unanimityMet
    /\ state' = "DECIDED"
    /\ successCount' = sc_
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED]-> DELIBERATING
CollectingVotesToDeliberating(sc_) ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "DELIBERATING"
    /\ successCount' = sc_
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / unanimityMet]-> DECIDED
DeliberatingToDecidedGuarded(sc_) ==
    /\ state = "DELIBERATING"
    /\ sc_ = polledCount  \* guard: unanimityMet
    /\ state' = "DECIDED"
    /\ successCount' = sc_
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / noInfiniteDeliberation]-> DELIBERATING
DeliberatingToDeliberating ==
    /\ state = "DELIBERATING"
    /\ deliberationRounds < maxDeliberation  \* guard: noInfiniteDeliberation
    /\ state' = "DELIBERATING"
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, successCount, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED]-> DECIDED (no guard, fallthrough)
DeliberatingToDecided ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[DECIDE]-> DECIDED
Decide ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED is a final (absorbing) state
StayDECIDED ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Next ──────────────────────────────────────────────────────────────────────
Next ==
    \/ \E sa_ \in 0..4 : QuorumStart(sa_)
    \/ \E sc_ \in 0..4 : CollectingVotesToDecidedGuarded(sc_)
    \/ \E sc_ \in 0..4 : CollectingVotesToDeliberating(sc_)
    \/ \E sc_ \in 0..4 : DeliberatingToDecidedGuarded(sc_)
    \/ DeliberatingToDeliberating
    \/ DeliberatingToDecided
    \/ Decide
    \/ StayDECIDED

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
