---- MODULE QGSDQuorum ----
(*
 * formal/tla/QGSDQuorum_xstate.tla
 * GENERATED by bin/xstate-to-tla.cjs
 * Source: src/machines/qgsd-workflow.machine.ts
 * Regenerate: node bin/xstate-to-tla.cjs src/machines/qgsd-workflow.machine.ts --config=formal/tla/guards/qgsd-workflow.json --module=QGSDQuorum
 * Generated: 2026-03-03
 *
 * XState machine id: qgsd-workflow
 * Initial state:     IDLE
 * States (4):          IDLE, COLLECTING_VOTES, DELIBERATING, DECIDED
 * Final states:      DECIDED
*)
EXTENDS Naturals, FiniteSets, TLC

\* ── Variables ────────────────────────────────────────────────────────────────
VARIABLES
    state,  \* FSM state
    slotsAvailable,  \* default: 0  annotation: event
    successCount,  \* default: 0  annotation: event
    deliberationRounds,  \* default: 0  annotation: deliberationRounds + 1
    maxDeliberation,  \* default: 9  annotation: const
    maxSize,  \* default: 3  annotation: (no annotation)
    polledCount  \* default: 0  annotation: (no annotation)

vars == <<state, slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Type invariant ────────────────────────────────────────────────────────────
TypeOK ==
    /\ state \in {"IDLE", "COLLECTING_VOTES", "DELIBERATING", "DECIDED"}
    /\ slotsAvailable \in Nat  \* FIXME: tighten bound if needed
    /\ successCount \in Nat  \* FIXME: tighten bound if needed
    /\ deliberationRounds \in Nat  \* FIXME: tighten bound if needed
    /\ maxDeliberation \in Nat  \* FIXME: tighten bound if needed
    /\ maxSize \in Nat  \* FIXME: tighten bound if needed
    /\ polledCount \in Nat  \* FIXME: tighten bound if needed

\* ── Initial state ─────────────────────────────────────────────────────────────
Init ==
    /\ state = "IDLE"
    /\ slotsAvailable = 0
    /\ successCount = 0
    /\ deliberationRounds = 0
    /\ maxDeliberation = 9
    /\ maxSize = 3
    /\ polledCount = 0

\* ── Actions ────────────────────────────────────────────────────────────────────

\* IDLE -[QUORUM_START]-> COLLECTING_VOTES
QuorumStart(slotsAvailable) ==
    /\ state = "IDLE"
    /\ state' = "COLLECTING_VOTES"
    /\ slotsAvailable' = slotsAvailable  \* param from event
    /\ polledCount' = polledCount  \* FIXME: XState assign for polledCount
    /\ UNCHANGED <<successCount, deliberationRounds, maxDeliberation, maxSize>>

\* COLLECTING_VOTES -[VOTES_COLLECTED / unanimityMet]-> DECIDED
CollectingVotesVotesCollectedToDECIDED(successCount) ==
    /\ state = "COLLECTING_VOTES"
    /\ successCount = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = successCount  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* COLLECTING_VOTES -[VOTES_COLLECTED]-> DELIBERATING
CollectingVotesVotesCollectedToDELIBERATING(successCount) ==
    /\ state = "COLLECTING_VOTES"
    /\ state' = "DELIBERATING"
    /\ successCount' = successCount  \* param from event
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / unanimityMet]-> DECIDED
DeliberatingVotesCollectedToDECIDED(successCount) ==
    /\ state = "DELIBERATING"
    /\ successCount = polledCount
    /\ state' = "DECIDED"
    /\ successCount' = successCount  \* param from event
    /\ UNCHANGED <<slotsAvailable, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED / noInfiniteDeliberation]-> DELIBERATING
DeliberatingVotesCollectedToDELIBERATING ==
    /\ state = "DELIBERATING"
    /\ deliberationRounds < MaxDeliberation
    /\ state' = "DELIBERATING"
    /\ deliberationRounds' = deliberationRounds + 1
    /\ UNCHANGED <<slotsAvailable, successCount, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[VOTES_COLLECTED]-> DECIDED
DeliberatingVotesCollectedToDECIDED ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DELIBERATING -[DECIDE]-> DECIDED
Decide ==
    /\ state = "DELIBERATING"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* DECIDED is a final (absorbing) state
StayDECIDED ==
    /\ state = "DECIDED"
    /\ state' = "DECIDED"
    /\ UNCHANGED <<slotsAvailable, successCount, deliberationRounds, maxDeliberation, maxSize, polledCount>>

\* ── Next ──────────────────────────────────────────────────────────────────────
Next ==
    \/ \E slotsAvailable \in Nat : QuorumStart(slotsAvailable)
    \/ \E successCount \in Nat : CollectingVotesVotesCollectedToDECIDED(successCount)
    \/ \E successCount \in Nat : CollectingVotesVotesCollectedToDELIBERATING(successCount)
    \/ \E successCount \in Nat : DeliberatingVotesCollectedToDECIDED(successCount)
    \/ DeliberatingVotesCollectedToDELIBERATING
    \/ DeliberatingVotesCollectedToDECIDED
    \/ Decide
    \/ StayDECIDED

\* ── Specification ─────────────────────────────────────────────────────────────
Spec == Init /\ [][Next]_vars
        /\ WF_vars(QuorumStart)
        /\ WF_vars(CollectingVotesVotesCollectedToDECIDED)
        /\ WF_vars(CollectingVotesVotesCollectedToDELIBERATING)
        /\ WF_vars(DeliberatingVotesCollectedToDECIDED)
        /\ WF_vars(DeliberatingVotesCollectedToDELIBERATING)
        /\ WF_vars(Decide)
        /\ WF_vars(StayDECIDED)

\* ── Invariants (add domain-specific properties here) ──────────────────────────
\* TypeOK is the structural baseline. Add semantic invariants below.

====
